export type ContractClause = {
  id: string
  title: string
  content: string
  enabled: boolean
  fixed: boolean
  order: number
}

export const DEFAULT_CLAUSES: ContractClause[] = [
  { id: 'workmanship', title: 'Workmanship', enabled: true, fixed: false, order: 0, content: 'All work will be completed in a professional manner according to industry standard practices. Any changes to the scope of work must be agreed upon in writing and may result in additional charges. Oral representations by the Company or its representatives do not form part of this Agreement.' },
  { id: 'payment_terms', title: 'Payment terms', enabled: true, fixed: false, order: 1, content: 'A deposit is required to confirm your order and schedule installation. The remaining balance is due upon completion of work. All materials remain the property of the Company until payment is received in full.' },
  { id: 'cancellation', title: 'Cancellation policy', enabled: true, fixed: false, order: 2, content: 'Either party may cancel this contract with 72 hours written notice prior to the scheduled start date. If the Customer cancels after materials have been ordered, the deposit is non-refundable.' },
  { id: 'customer_responsibilities', title: 'Customer responsibilities', enabled: true, fixed: false, order: 3, content: 'Prior to installation, the Customer must provide clear access (minimum 3 feet) to all window and door openings, remove blinds, curtains, and furniture, and cover personal belongings from dust. All artwork and fragile items must be removed from the work area. The Customer must notify the installer if any old windows or doors are to be kept; otherwise they will be disposed of.' },
  { id: 'damage_disclaimer', title: 'Damage disclaimer', enabled: true, fixed: false, order: 4, content: 'Although care is taken during every installation, the Company is not liable for incidental damage to exterior materials such as stucco, siding, or plaster that may occur as a result of installation.' },
  { id: 'permits', title: 'Permits responsibility', enabled: true, fixed: false, order: 5, content: "The Customer is solely responsible for obtaining any required building permits and ensuring compliance with all applicable by-laws and building codes. The Company will inform the Customer of Fire Code requirements for bedroom windows but is not responsible for the Customer's choice not to comply." },
  { id: 'interior_finishing', title: 'Interior finishing', enabled: true, fixed: false, order: 6, content: 'The Company is not responsible for painting, patching drywall, or repairing any interior surfaces around windows and doors after installation. The Customer is responsible for all interior touch-ups, caulking, and painting of wood jamb and casing.' },
  { id: 'custom_order', title: 'Custom order policy', enabled: true, fixed: false, order: 7, content: 'All products are manufactured to custom sizes and specifications and cannot be returned, restocked, or reused. Once an order has entered production, cancellations or changes are not permitted. The Customer will be invoiced for any portion of the order already manufactured.' },
  { id: 'force_majeure', title: 'Force majeure', enabled: true, fixed: false, order: 8, content: 'The Company is not responsible for delays caused by circumstances beyond its control, including fire, flood, strikes, supplier delays, government actions, acts of God, or other similar events.' },
  { id: 'warranty_product', title: 'Manufacturer warranty', enabled: true, fixed: false, order: 9, content: 'All products supplied under this Agreement carry the manufacturer\'s limited warranty for the period stated in the project details of this Agreement. Manufacturer warranties cover defects in materials and product components, subject to the manufacturer\'s own terms and conditions, copies of which are available upon request. The Company will assist the Customer in submitting valid warranty claims to the manufacturer at no additional charge. Manufacturer warranties are void if products are misused, physically damaged, improperly maintained, modified after installation, or if full payment has not been received.' },
  { id: 'warranty_labour', title: 'Workmanship warranty', enabled: true, fixed: false, order: 10, content: 'The Company warrants all installation work against defects in workmanship for a period of one (1) year from the date of installation, unless a longer period is stated in the project details of this Agreement. If a defect in workmanship is identified during the warranty period, the Company will, at its sole discretion, repair or replace the affected work at no charge to the Customer. This warranty does not cover damage caused by misuse, neglect, or unauthorized modifications; normal wear and tear or structural settling; water infiltration not directly attributable to the installation; or work performed by third parties after completion. All warranty claims must be submitted in writing and are subject to on-site inspection by the Company. Warranty coverage is contingent on full payment having been received.' },
  { id: 'storage_fee', title: 'Storage fee', enabled: false, fixed: false, order: 10, content: 'If the Customer postpones or refuses the installation date after materials have been delivered, the Company reserves the right to charge a storage fee of $15 per day after a 2-week grace period.' },
  { id: 'interest_overdue', title: 'Interest on overdue amount', enabled: false, fixed: false, order: 11, content: 'Any amount not paid when due shall bear interest at the rate of 2% per month (24% per annum) from the due date until paid in full. The Customer shall also be liable for reasonable legal fees incurred in collection of overdue amounts.' },
  { id: 'indemnification', title: 'Indemnification', enabled: false, fixed: false, order: 12, content: "The Customer agrees to hold the Company harmless from any damages, injuries, or claims related directly or indirectly to the installation or supply of goods, except where caused by the Company's own negligence." },
  { id: 'liability_cap', title: 'Limitation of liability', enabled: true, fixed: false, order: 13, content: "To the maximum extent permitted by applicable law, the Company's total liability to the Customer for any claim arising out of or in connection with this Agreement — whether in contract, tort, or otherwise — shall not exceed the total amount paid by the Customer under this Agreement. The Company shall not be liable for indirect, special, incidental, or consequential damages of any kind, including loss of use, loss of income, or diminution in property value, even if the Company has been advised of the possibility of such damages. This limitation applies regardless of the form or basis of the claim." },
  { id: 'condensation', title: 'Condensation & humidity', enabled: true, fixed: false, order: 14, content: 'Condensation on window surfaces is a normal result of indoor humidity and temperature differences and does not constitute a product defect. The Customer is responsible for maintaining proper ventilation and humidity levels in the home.' },
  { id: 'window_accessories', title: 'Window accessories', enabled: false, fixed: false, order: 14, content: 'The Company does not guarantee that new windows will be compatible with existing blinds, shutters, drapes, or other window treatments. The Company is not liable for the functionality of existing accessories reinstalled on new windows.' },
  { id: 'concrete_cut', title: 'Concrete cut / structural modifications', enabled: false, fixed: false, order: 15, content: "Any enlargement of existing window openings requires engineered drawings and a municipal building permit at the Customer's expense. The Company is not liable for costs related to such permits or drawings." },
  { id: 'subcontractor_disclosure', title: 'Subcontractors', enabled: false, fixed: false, order: 16, content: 'The Company may engage qualified subcontractors to perform a portion of the work described in this Agreement. The Company remains solely responsible for the quality, safety, and completion of all work, whether performed by its own employees or by subcontractors. Subcontractors engaged by the Company are bound by the same standards of workmanship set out in this Agreement. The Customer will not be required to enter into any separate agreement with a subcontractor.' },
  { id: 'final_measurements', title: 'Final measurements', enabled: true, fixed: false, order: 17, content: 'Dimensions in this agreement are approximate and subject to change based on production and structural requirements. Final measurements will be confirmed by the installer within 10 days after the deposit is received. During measurements, the installer may need to remove existing casing or aluminum capping.' },
  { id: 'structural_issues', title: 'Structural issues', enabled: true, fixed: false, order: 18, content: 'In the event that previously unknown structural issues (including but not limited to rotten studs, deteriorated framing, or water damage) are discovered during installation, the Company may perform additional work to ensure proper completion. Such additional work will be subject to extra charges, which will be communicated to the Customer prior to proceeding.' },
  { id: 'old_windows_disposal', title: 'Old windows disposal', enabled: true, fixed: false, order: 19, content: 'The Customer must notify the installer prior to commencement of work if any existing windows or doors are to be kept. Unless otherwise specified, all removed windows, doors, and related materials will be disposed of by the Company at no additional charge.' },
  { id: 'ownership_of_goods', title: 'Ownership of goods', enabled: false, fixed: false, order: 20, content: 'All goods supplied under this Agreement remain the property of the Company until payment is received in full. Goods remain the property of the Company even if they become attached to or form part of the premises.' },
  { id: 'window_coverings', title: 'Window coverings & blinds', enabled: false, fixed: false, order: 21, content: "The Customer is responsible for removal and reinstallation of all blinds, curtains, shutters, and other window coverings unless otherwise specified. Existing window coverings may not fit new windows due to changes in frame depth or dimensions, and any required alterations are at the Customer's expense. The Company is not liable for damage to window coverings during removal or reinstallation." },
  { id: 'alarm_system', title: 'Alarm system', enabled: false, fixed: false, order: 22, content: 'The Customer is responsible for notifying the installer of any alarm systems or sensors on or near windows and doors prior to commencement of work. The Company is not responsible for alarm system removal, reinstallation, or any associated costs.' },
  { id: 'buyer_right_to_cancel', title: "Buyer's right to cancel", enabled: true, fixed: true, order: 23, content: 'You may cancel this contract from the day you enter into the contract until 10 days after you receive a copy of the contract. You do not need a reason to cancel. If you cancel, the seller has 15 days to refund your money. To cancel, you must give written notice by registered mail, fax, or personal delivery.' },
  { id: 'change_order', title: 'Change Orders', enabled: true, fixed: false, order: 24, content: 'Any changes to the scope of work after the signing of this Agreement — including but not limited to additional windows or doors, material upgrades, or modifications to existing specifications — must be documented in a written Change Order signed by both parties. A Change Order will specify the additional work, adjusted pricing, and any impact on the completion timeframe. No changes to the scope of work shall be binding until a Change Order has been signed by both parties.' },
  { id: 'site_access', title: 'Site Access', enabled: true, fixed: false, order: 26, content: 'The Client shall ensure reasonable site access during normal working hours for the Company and its installers, including adequate parking within a reasonable distance of the work zone. The Client shall also permit the temporary placement of waste containers, material bins, or storage equipment near the designated work area as necessary for the safe and efficient completion of the project.' },
  { id: 'dispute_resolution', title: 'Dispute resolution', enabled: true, fixed: false, order: 27, content: 'In the event of a dispute arising out of or in connection with this Agreement, the parties agree to first attempt resolution through good-faith negotiation within 30 days of written notice of the dispute. If negotiation does not resolve the matter, the parties agree to submit to non-binding mediation administered in the Province of {{PROVINCE}} before commencing any legal proceedings. The cost of mediation shall be shared equally by the parties unless otherwise agreed in writing. This Agreement shall be governed by the laws of the Province of {{PROVINCE}}, without regard to conflict of law principles, and the parties irrevocably submit to the exclusive jurisdiction of the courts of {{PROVINCE}} for any dispute not resolved through the foregoing process.' },
  { id: 'entire_agreement', title: 'Entire Agreement', enabled: true, fixed: false, order: 28, content: 'This Agreement constitutes the entire agreement between the parties with respect to its subject matter and supersedes all prior and contemporaneous agreements, representations, and understandings, whether written or oral. If any provision of this Agreement is held to be invalid, illegal, or unenforceable, the remaining provisions shall continue in full force and effect.' },
]

/**
 * Returns the contractor's saved clauses, or DEFAULT_CLAUSES when the profile
 * value is null / empty / unparseable (i.e. user has never opened Settings → Contract).
 * Does NOT write anything to the database.
 */
export function getEffectiveClauses(raw: string | unknown[] | null | undefined): ContractClause[] {
  if (Array.isArray(raw) && raw.length > 0) return raw as ContractClause[]
  if (raw && typeof raw === 'string') {
    try {
      const parsed = JSON.parse(raw)
      if (Array.isArray(parsed) && parsed.length > 0) return parsed as ContractClause[]
    } catch {}
  }
  return DEFAULT_CLAUSES
}
