export type ContractClause = {
  id: string
  title: string
  content: string
  enabled: boolean
  fixed: boolean
  order: number
}

export const DEFAULT_CLAUSES: ContractClause[] = [
  { id: 'workmanship', title: 'Workmanship', enabled: true, fixed: false, order: 0, content: 'All work will be completed in a professional manner according to industry standard practices. Any changes to the scope of work must be agreed upon in writing and may result in additional charges. Oral representations by the Company or its representatives do not form part of this Agreement.' },
  { id: 'payment_terms', title: 'Payment terms', enabled: true, fixed: false, order: 1, content: 'A deposit is required to confirm your order and schedule installation. The remaining balance is due upon completion of work. All materials remain the property of the Company until payment is received in full.' },
  { id: 'cancellation', title: 'Cancellation policy', enabled: true, fixed: false, order: 2, content: 'Either party may cancel this contract with 72 hours written notice prior to the scheduled start date. If the Customer cancels after materials have been ordered, the deposit is non-refundable.' },
  { id: 'customer_responsibilities', title: 'Customer responsibilities', enabled: true, fixed: false, order: 3, content: 'Prior to installation, the Customer must provide clear access (minimum 3 feet) to all window and door openings, remove blinds, curtains, and furniture, and cover personal belongings from dust. All artwork and fragile items must be removed from the work area. The Customer must notify the installer if any old windows or doors are to be kept; otherwise they will be disposed of.' },
  { id: 'damage_disclaimer', title: 'Damage disclaimer', enabled: true, fixed: false, order: 4, content: 'Although care is taken during every installation, the Company is not liable for incidental damage to exterior materials such as stucco, siding, or plaster that may occur as a result of installation.' },
  { id: 'permits', title: 'Permits responsibility', enabled: true, fixed: false, order: 5, content: "The Customer is solely responsible for obtaining any required building permits and ensuring compliance with all applicable by-laws and building codes. The Company will inform the Customer of Fire Code requirements for bedroom windows but is not responsible for the Customer's choice not to comply." },
  { id: 'interior_finishing', title: 'Interior finishing', enabled: true, fixed: false, order: 6, content: 'The Company is not responsible for painting, patching drywall, or repairing any interior surfaces around windows and doors after installation. The Customer is responsible for all interior touch-ups, caulking, and painting of wood jamb and casing.' },
  { id: 'custom_order', title: 'Custom order policy', enabled: true, fixed: false, order: 7, content: 'All products are manufactured to custom sizes and specifications and cannot be returned, restocked, or reused. Once an order has entered production, cancellations or changes are not permitted. The Customer will be invoiced for any portion of the order already manufactured.' },
  { id: 'force_majeure', title: 'Force majeure', enabled: true, fixed: false, order: 8, content: 'The Company is not responsible for delays caused by circumstances beyond its control, including fire, flood, strikes, supplier delays, government actions, acts of God, or other similar events.' },
  { id: 'warranty', title: 'Warranty', enabled: true, fixed: false, order: 9, content: 'The Company warrants its workmanship for the period specified on the estimate. Manufacturer warranties apply to all products as provided. Warranty is void if products are misused, improperly maintained, or payment has not been received in full.' },
  { id: 'storage_fee', title: 'Storage fee', enabled: false, fixed: false, order: 10, content: 'If the Customer postpones or refuses the installation date after materials have been delivered, the Company reserves the right to charge a storage fee of $15 per day after a 2-week grace period.' },
  { id: 'interest_overdue', title: 'Interest on overdue amount', enabled: false, fixed: false, order: 11, content: 'Any amount not paid when due shall bear interest at the rate of 2% per month (24% per annum) from the due date until paid in full. The Customer shall also be liable for reasonable legal fees incurred in collection of overdue amounts.' },
  { id: 'indemnification', title: 'Indemnification', enabled: false, fixed: false, order: 12, content: "The Customer agrees to hold the Company harmless from any damages, injuries, or claims related directly or indirectly to the installation or supply of goods, except where caused by the Company's own negligence." },
  { id: 'condensation', title: 'Condensation & humidity', enabled: false, fixed: false, order: 13, content: 'Condensation on window surfaces is a normal result of indoor humidity and temperature differences and does not constitute a product defect. The Customer is responsible for maintaining proper ventilation and humidity levels in the home.' },
  { id: 'window_accessories', title: 'Window accessories', enabled: false, fixed: false, order: 14, content: 'The Company does not guarantee that new windows will be compatible with existing blinds, shutters, drapes, or other window treatments. The Company is not liable for the functionality of existing accessories reinstalled on new windows.' },
  { id: 'concrete_cut', title: 'Concrete cut / structural modifications', enabled: false, fixed: false, order: 15, content: "Any enlargement of existing window openings requires engineered drawings and a municipal building permit at the Customer's expense. The Company is not liable for costs related to such permits or drawings." },
  { id: 'final_measurements', title: 'Final measurements', enabled: true, fixed: false, order: 17, content: 'Dimensions in this agreement are approximate and subject to change based on production and structural requirements. Final measurements will be confirmed by the installer within 10 days after the deposit is received. During measurements, the installer may need to remove existing casing or aluminum capping.' },
  { id: 'structural_issues', title: 'Structural issues', enabled: true, fixed: false, order: 18, content: 'In the event that previously unknown structural issues (including but not limited to rotten studs, deteriorated framing, or water damage) are discovered during installation, the Company may perform additional work to ensure proper completion. Such additional work will be subject to extra charges, which will be communicated to the Customer prior to proceeding.' },
  { id: 'old_windows_disposal', title: 'Old windows disposal', enabled: true, fixed: false, order: 19, content: 'The Customer must notify the installer prior to commencement of work if any existing windows or doors are to be kept. Unless otherwise specified, all removed windows, doors, and related materials will be disposed of by the Company at no additional charge.' },
  { id: 'ownership_of_goods', title: 'Ownership of goods', enabled: false, fixed: false, order: 20, content: 'All goods supplied under this Agreement remain the property of the Company until payment is received in full. Goods remain the property of the Company even if they become attached to or form part of the premises.' },
  { id: 'window_coverings', title: 'Window coverings & blinds', enabled: false, fixed: false, order: 21, content: "The Customer is responsible for removal and reinstallation of all blinds, curtains, shutters, and other window coverings unless otherwise specified. Existing window coverings may not fit new windows due to changes in frame depth or dimensions, and any required alterations are at the Customer's expense. The Company is not liable for damage to window coverings during removal or reinstallation." },
  { id: 'alarm_system', title: 'Alarm system', enabled: false, fixed: false, order: 22, content: 'The Customer is responsible for notifying the installer of any alarm systems or sensors on or near windows and doors prior to commencement of work. The Company is not responsible for alarm system removal, reinstallation, or any associated costs.' },
  { id: 'buyer_right_to_cancel', title: "Buyer's right to cancel", enabled: true, fixed: true, order: 23, content: 'You may cancel this contract from the day you enter into the contract until 10 days after you receive a copy of the contract. You do not need a reason to cancel. If you cancel, the seller has 15 days to refund your money. To cancel, you must give written notice by registered mail, fax, or personal delivery.' },
]
